<a href="https://colab.research.google.com/github/zeerau/TDI_Projects/blob/main/week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json

with open('/content/employees_data.json', 'r') as f:
  data = json.load(f)

# 1. Unique departments
departments = set()
for employee in data:
  departments.add(employee['department'])
num_departments = len(departments)
print(f"Number of unique departments: {num_departments}")

# 2. Top 5 highest-paid employees
sorted_employees = sorted(data, key=lambda x: x['salary'], reverse=True)
top_5_employees = sorted_employees[:5]
print(f"Top 5 highest-paid employees: {top_5_employees}")

# 3. Average monthly salary
total_salary = sum(int(employee['salary'].replace('N ', '')) for employee in data)
average_salary = total_salary / len(data)
print(f"Average monthly salary: {average_salary}")

# 4. Employees per department
department_counts = {}
for employee in data:
  department = employee['department']
  department_counts[department] = department_counts.get(department, 0) + 1
print(f"Employees per department: {department_counts}")

# 5. Employees ranked by salary within each department
departments = {}
for employee in data:
  department = employee['department']
  if department not in departments:
    departments[department] = []
  departments[department].append(employee)

for department, employees in departments.items():
  sorted_employees = sorted(employees, key=lambda x: x['salary'], reverse=True)
  print(f"Employees in {department} ranked by salary:")
  for employee in sorted_employees:
    if 'name' in employee:
      print(f"{employee['name']} - {employee['salary']}")
    else:
      print(f"Employee with ID {employee.get('empID', 'Unknown')} - {employee['salary']}") # Print employee ID if name is not available


# 6. Total monthly payroll expense
total_payroll = sum(int(employee['salary'].replace('N ', '')) for employee in data)
print(f"Total monthly payroll expense: {total_payroll}")

# 7. Highest and lowest salary
# highest_salary = max(data, key=lambda x: x['salary'])
# lowest_salary = min(data, key=lambda x: x['salary'])
# # Check if 'name' key exists before accessing it
# print(f"Highest salary: {highest_salary.get('name', highest_salary.get('fullName', f'Employee with ID {highest_salary.get("empID", "Unknown")}'))} - {highest_salary['salary']}")
# print(f"Lowest salary: {lowest_salary.get('name', lowest_salary.get('fullName', f'Employee with ID {lowest_salary.get("empID", "Unknown")}'))} - {lowest_salary['salary']}")
# 8. Remove Junior employees and count remaining
# Add code to remove Junior employees and count remaining employees here
data = [employee for employee in data if employee['experienceLevel'] != 'Junior']
remaining_employees = len(data)
print(f"Number of employees after removing Juniors: {remaining_employees}")

Number of unique departments: 8
Top 5 highest-paid employees: [{'empID': 'E015', 'fullName': 'George Walker', 'department': 'Legal', 'position': 'Legal Advisor', 'experienceLevel': 'Senior', 'salary': 'N 900000'}, {'empID': 'E037', 'fullName': 'Henry Hill', 'department': 'Sales', 'position': 'Sales Director', 'experienceLevel': 'Senior', 'salary': 'N 900000'}, {'empID': 'E043', 'fullName': 'Oliver Lopez', 'department': 'Legal', 'position': 'Legal Counsel', 'experienceLevel': 'Senior', 'salary': 'N 900000'}, {'empID': 'E047', 'fullName': 'Noah Mitchell', 'department': 'IT', 'position': 'Cloud Architect', 'experienceLevel': 'Senior', 'salary': 'N 900000'}, {'empID': 'E005', 'fullName': 'Michael Davis', 'department': 'IT', 'position': 'Software Engineer', 'experienceLevel': 'Senior', 'salary': 'N 850000'}]
Average monthly salary: 637000.0
Employees per department: {'Finance': 8, 'Human Resources': 2, 'IT': 8, 'Marketing': 8, 'Sales': 6, 'Operations': 6, 'Customer Service': 6, 'Legal': 6}
Employees in Finance ranked by salary:
Employee with ID E046 - N 800000
Employee with ID E001 - N 750000
Employee with ID E032 - N 720000
Employee with ID E031 - N 700000
Employee with ID E045 - N 670000
Employee with ID E018 - N 630000
Employee with ID E017 - N 620000
Employee with ID E002 - N 600000
Employees in Human Resources ranked by salary:
Employee with ID E003 - N 700000
Employee with ID E004 - N 400000
Employees in IT ranked by salary:
Employee with ID E047 - N 900000
Employee with ID E005 - N 850000
Employee with ID E033 - N 850000
Employee with ID E020 - N 820000
Employee with ID E019 - N 750000
Employee with ID E034 - N 750000
Employee with ID E006 - N 700000
Employee with ID E048 - N 400000
Employees in Marketing ranked by salary:
Employee with ID E035 - N 680000
Employee with ID E050 - N 620000
Employee with ID E049 - N 600000
Employee with ID E007 - N 550000
Employee with ID E021 - N 550000
Employee with ID E036 - N 550000
Employee with ID E008 - N 450000
Employee with ID E022 - N 420000
Employees in Sales ranked by salary:
Employee with ID E037 - N 900000
Employee with ID E009 - N 850000
Employee with ID E023 - N 650000
Employee with ID E010 - N 400000
Employee with ID E024 - N 400000
Employee with ID E038 - N 380000
Employees in Operations ranked by salary:
Employee with ID E025 - N 850000
Employee with ID E011 - N 800000
Employee with ID E012 - N 600000
Employee with ID E039 - N 580000
Employee with ID E026 - N 520000
Employee with ID E040 - N 450000
Employees in Customer Service ranked by salary:
Employee with ID E013 - N 700000
Employee with ID E041 - N 700000
Employee with ID E042 - N 550000
Employee with ID E027 - N 540000
Employee with ID E028 - N 380000
Employee with ID E014 - N 350000
Employees in Legal ranked by salary:
Employee with ID E015 - N 900000
Employee with ID E043 - N 900000
Employee with ID E029 - N 800000
Employee with ID E030 - N 620000
Employee with ID E016 - N 600000
Employee with ID E044 - N 400000
Total monthly payroll expense: 31850000
Number of employees after removing Juniors: 39